name: Deploy FrontEnd
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build y Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Usa Node ultima versión
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instala dependencias
        run:  npm ci
      - name: Build
        run:  npm run build:ci
      - name: Test
        run:  npm run test:ci
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with: 
            name: deploy_dist
            path: dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          coverage: coverage
  deploy:
    runs-on: ubuntu-latest
    needs:  build
    steps:  
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/angular-demo
          
